# Generated by Django 5.0.1 on 2024-01-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
  
        
    ]
