# Generated by Django 5.0.1 on 2024-01-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20240110_0036'),
    ]

    operations = [
    ]
