//register diispatch
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAILS='REGISTER_FAILS';
//EMAIL checheck
export const EMAIL_EXISTS='EMAIL_EXISTS';
//login dipatch
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
//logout dispatch
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGOUT_FAIL='LOGOUT_FAIL';
//authcation dispatch
export const AUTHENTICATION_SUCCESS='AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL='AUTHENTICATION_FAIL';
//delete dispatch 
export const DELETE_ACCOUNT_SUCCESS='DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAIL='DELETE_ACCOUNT_FAIL';
//profile dispatch 
export const USERPROFILE_SUCCESS='USERPROFILE_SUCCESS';
export const USERPROFILE_FAIL='USERPROFILE_FAIL';
//update dispatch
export const UPDATE_USERPROFILE_SUCCESS='UPDATE_USERPROFILE_SUCCESS';
export const UPDATE_USERPROFILE_FAIL='UPDATE_USERPROFILE_FAIL';

export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';

